package rules;

import com.example.drools.rule.engine.model.RulesRequestDetails;
import com.example.drools.rule.engine.model.RulesResponse;

rule "self Approval Rule"
dialect "mvel"

when
    request : RulesRequestDetails(empId in ("19629","2195244","1976352","S204","M1044588","1976353"))
    response : RulesResponse()

then
    
    response.setStatus("Success");
    response.setMessage("Rules fired");
    response.setRuleMessage("Employee eligible for self approval");
    response.setSelfApproval(true);

end
